# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('d', '草稿'), ('p', '发布')], default='d', max_length=1, verbose_name='文章状态'),
        ),
    ]
