# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='归档年份')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.BlogYear', verbose_name='归档年份'),
        ),
    ]
