# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Blog', verbose_name='评论所属文章'),
        ),
    ]
